# Generated by Django 3.2.16 on 2023-03-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_alter_post_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="description",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
