# Generated by Django 3.2.16 on 2023-03-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_group_description"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                fields=("following", "user"), name="unique_user_following"
            ),
        ),
    ]
